version: '3'
services:
  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
      - "80:80"
      - "433:433"
    volumes:
      - ${CODE_DIR}:/code
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php      
  php:
    build: .
    volumes:  
      - ${CODE_DIR}:/code
  composer:
    image: composer:latest
    command: install
    working_dir: /code
    volumes:
      - ${CODE_DIR}:/code
    
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql:db
    ports:
      - "8082:80"
    environment:
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - PHP_UPLOAD_MAX_FILESIZE=100MB
      - PMA_PORT=3306